
package Menus;

import clases.comandos;
import clases.conexion;
import clases.configuracion;
import com.toedter.calendar.JTextFieldDateEditor;
import java.awt.Color;
import java.awt.Component;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class Compras extends javax.swing.JPanel {

    conexion co = new conexion();
    comandos c = new comandos();
    configuracion conf = new configuracion();
    String cod_prov = "";
    String aux[] = new String[0];
    Component temp;
    Component temp2;
    
    public Compras() {
        initComponents();
        co.Conexion();
        cantidad.requestFocus();    
        
        JTextFieldDateEditor editor = (JTextFieldDateEditor) fecha.getDateEditor();
        editor.setEditable(false);
        editor.setText(c.fecha_servidor());
        editor.setBackground(Color.white);
        temp = panel.getComponentAt(2);        
        temp2 = panel.getComponentAt(1);
        panel.removeTabAt(1);
        panel.removeTabAt(1);
    }
    
    
    public void CargaProductos(){
        int p = 0;
        aux= new String[0];
        DefaultTableModel md = (DefaultTableModel)registros_productos.getModel();
        md.setRowCount(0);
        ResultSet s = c.consulta("select p.PROD_CODIGO,p.PROD_DESCRIPCION,p.PROD_STOCK,p.PROD_PRECIO_UNITARIO,pr.prov_descripcion,p.PROV_CODIGO \n" +
        "from productos p, proveedores pr where pr.prov_codigo=p.prov_codigo and p.prod_estado='AC' order by PROD_CODIGO asc");
        try {
            while(s.next()){
                Object v[]= new Object[5];
                v[0]=s.getObject(1);
                v[1]=s.getObject(2);
                v[2]=s.getObject(3);
                v[3]=s.getObject(4);
                v[4]=s.getObject(5);
                aux = Arrays.copyOf(aux, aux.length + 1);
                aux[p]=String.valueOf(s.getObject(6));
                p++;
                md.addRow(v);
            }
            registros_productos.setModel(md);
        } catch (SQLException ex) {
            Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage(), "ERROR",JOptionPane.ERROR_MESSAGE);
            
        }
    }
    
    public void CargaTablaProveeedor(){
        DefaultTableModel model = (DefaultTableModel) registros_proveedores.getModel();
        model.setRowCount(0);
        Object vector[]= new Object[2];
        try {                
            ResultSet aux =  c.consulta("select PROV_CODIGO,PROV_DESCRIPCION from proveedores where PROV_ESTADO='AC' order by PROV_CODIGO asc");
            while(aux.next()){
                for(int i=0;i<2;i++){
                    vector[i] = aux.getObject(i+1);
                }
                model.addRow(vector);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Compras.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage(), "ERROR",JOptionPane.ERROR_MESSAGE);
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JTabbedPane();
        ventana_principal = new javax.swing.JPanel();
        cantidad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        descripcion = new javax.swing.JTextField();
        precio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        codigo = new javax.swing.JTextField();
        proveedor = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        guardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        fecha = new com.toedter.calendar.JDateChooser();
        productos = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        filtro_productos = new javax.swing.JComboBox<>();
        campo_productos = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        registros_productos = new javax.swing.JTable();
        ventana_buscar = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        filtro = new javax.swing.JComboBox<>();
        campo = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        registros_proveedores = new javax.swing.JTable();

        panel.setForeground(new java.awt.Color(51, 51, 51));
        panel.setFont(new java.awt.Font("Decker", 1, 18)); // NOI18N

        cantidad.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jLabel2.setText("DESCRIPCION:");

        jLabel5.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jLabel5.setText("PROVEEDOR:");

        jLabel4.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jLabel4.setText("PRECIO:");

        descripcion.setEditable(false);
        descripcion.setBackground(new java.awt.Color(255, 255, 255));
        descripcion.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        descripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                descripcionKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                descripcionKeyTyped(evt);
            }
        });

        precio.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jLabel3.setText("CANTIDAD COMPRADA:");

        jLabel7.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jLabel7.setText("CODIGO PRODUCTO:");

        codigo.setEditable(false);
        codigo.setBackground(new java.awt.Color(255, 255, 255));
        codigo.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N

        proveedor.setEditable(false);
        proveedor.setBackground(new java.awt.Color(255, 255, 255));
        proveedor.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N

        buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buscar.png"))); // NOI18N
        buscar.setBorder(null);
        buscar.setBorderPainted(false);
        buscar.setContentAreaFilled(false);
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/seleccionar.png"))); // NOI18N
        jButton2.setAutoscrolls(true);
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancelar.png"))); // NOI18N
        cancelar.setBorder(null);
        cancelar.setBorderPainted(false);
        cancelar.setContentAreaFilled(false);
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/guardar.png"))); // NOI18N
        guardar.setBorder(null);
        guardar.setBorderPainted(false);
        guardar.setContentAreaFilled(false);
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jLabel1.setText("FECHA:");

        fecha.setBackground(new java.awt.Color(255, 255, 255));
        fecha.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N

        javax.swing.GroupLayout ventana_principalLayout = new javax.swing.GroupLayout(ventana_principal);
        ventana_principal.setLayout(ventana_principalLayout);
        ventana_principalLayout.setHorizontalGroup(
            ventana_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventana_principalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ventana_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ventana_principalLayout.createSequentialGroup()
                        .addGroup(ventana_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ventana_principalLayout.createSequentialGroup()
                                .addGroup(ventana_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(25, 25, 25)
                                .addGroup(ventana_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(descripcion)
                                    .addComponent(cantidad)
                                    .addComponent(precio)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventana_principalLayout.createSequentialGroup()
                                        .addComponent(proveedor)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buscar)
                                        .addGap(4, 4, 4))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventana_principalLayout.createSequentialGroup()
                                        .addComponent(codigo)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton2)))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventana_principalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                        .addGroup(ventana_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventana_principalLayout.createSequentialGroup()
                                .addGap(268, 268, 268)
                                .addComponent(jLabel1)
                                .addGap(42, 42, 42)
                                .addComponent(fecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventana_principalLayout.createSequentialGroup()
                                .addComponent(cancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                                .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(167, Short.MAX_VALUE))))))
        );
        ventana_principalLayout.setVerticalGroup(
            ventana_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventana_principalLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(ventana_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(ventana_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addGroup(ventana_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(ventana_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(ventana_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(ventana_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(ventana_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ventana_principalLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(ventana_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ventana_principalLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(buscar)))
                .addGap(26, 26, 26)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ventana_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(guardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );

        panel.addTab("COMPRAS", ventana_principal);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cuadro de Búsqueda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 18))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("Filtrar por:");

        filtro_productos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        filtro_productos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Codigo", "Descripcion" }));
        filtro_productos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                filtro_productosItemStateChanged(evt);
            }
        });

        campo_productos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_productos.setText("Ingrese Valor de Busqueda....");
        campo_productos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campo_productosFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campo_productosFocusLost(evt);
            }
        });
        campo_productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_productosActionPerformed(evt);
            }
        });
        campo_productos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campo_productosKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_productosKeyTyped(evt);
            }
        });

        registros_productos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        registros_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "DESCRIPCION", "STOCK", "PRECIO", "PROVEEDOR"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        registros_productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registros_productosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(registros_productos);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(filtro_productos, 0, 166, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(campo_productos, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(filtro_productos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campo_productos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout productosLayout = new javax.swing.GroupLayout(productos);
        productos.setLayout(productosLayout);
        productosLayout.setHorizontalGroup(
            productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        productosLayout.setVerticalGroup(
            productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panel.addTab("PRODUCTOS", productos);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cuadro de Búsqueda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 18))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("Filtrar por:");

        filtro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        filtro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Codigo", "Nombres" }));
        filtro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                filtroItemStateChanged(evt);
            }
        });

        campo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo.setText("Ingrese Valor de Busqueda....");
        campo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoFocusLost(evt);
            }
        });
        campo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoActionPerformed(evt);
            }
        });
        campo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoKeyTyped(evt);
            }
        });

        registros_proveedores.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        registros_proveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "NOMBRES Y APELLIDOS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        registros_proveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registros_proveedoresMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(registros_proveedores);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(filtro, 0, 166, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(campo, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(filtro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout ventana_buscarLayout = new javax.swing.GroupLayout(ventana_buscar);
        ventana_buscar.setLayout(ventana_buscarLayout);
        ventana_buscarLayout.setHorizontalGroup(
            ventana_buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventana_buscarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        ventana_buscarLayout.setVerticalGroup(
            ventana_buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventana_buscarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panel.addTab("PROVEEDORES", ventana_buscar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 711, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(panel)
                    .addGap(0, 0, 0)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 438, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(panel)
                    .addGap(0, 0, 0)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void descripcionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_descripcionKeyReleased

    }//GEN-LAST:event_descripcionKeyReleased

    private void descripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_descripcionKeyTyped
        char n = evt.getKeyChar();
        if(Character.isLetter(n)){
            String cad = (""+n).toUpperCase();
            n=cad.charAt(0);
            evt.setKeyChar(n);
        }
    }//GEN-LAST:event_descripcionKeyTyped

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        CargaTablaProveeedor();

        panel.add(temp.getName(),temp);
        panel.setTitleAt(1, "PROVEEDORES");
        panel.setSelectedIndex(1);

        campo.requestFocus();
    }//GEN-LAST:event_buscarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        CargaProductos();
        panel.add(temp2.getName(),temp2);
        panel.setTitleAt(1, "PRODUCTOS");
        panel.setSelectedIndex(1);

        campo.requestFocus();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        descripcion.requestFocus();
        conf.borrar_texto(new Object[]{codigo,descripcion,cantidad,precio,proveedor});
        cantidad.setEnabled(true);
        JTextFieldDateEditor editor = (JTextFieldDateEditor) fecha.getDateEditor();
        editor.setEditable(false);
        editor.setText(c.fecha_servidor());
    }//GEN-LAST:event_cancelarActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        if(proveedor.getText().trim().length()>0){
            SimpleDateFormat sd = new SimpleDateFormat("dd/MM/YYYY");
            String nom = descripcion.getText();
            String cantidad_comprada = cantidad.getText();
            String Precio = precio.getText();
            try {
                c.ejecutar("call PROC_COMPRA_PRODUCTO('"+nom+"',TO_DATE('"+sd.format(fecha.getDate())+"','DD/MM/YYYY'),"+Precio+","+cantidad_comprada+","+codigo.getText()+","+cod_prov+")");
                conf.mensaje(3,"Se ha agregado correctamente","Programa");
                cancelar.doClick();
            } catch (SQLException ex) {
                Logger.getLogger(Compras.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, ex.getMessage(), "ERROR",JOptionPane.ERROR_MESSAGE);
            }

        }else{
            conf.mensaje(2,"Debe seleccionar al menos un proveedor","Programa");
        }
    }//GEN-LAST:event_guardarActionPerformed

    private void filtro_productosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_filtro_productosItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_filtro_productosItemStateChanged

    private void campo_productosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campo_productosFocusGained
        if(campo_productos.getText().trim().toLowerCase().equals("ingrese valor de busqueda....")){
            campo_productos.setText("");
        }
    }//GEN-LAST:event_campo_productosFocusGained

    private void campo_productosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campo_productosFocusLost
        if( campo_productos.getText().trim().equals("") || campo_productos.getText().trim().toLowerCase().equals("ingrese valor de busqueda....")){
            campo_productos.setText("Ingrese Valor de Busqueda....");
        }
    }//GEN-LAST:event_campo_productosFocusLost

    private void campo_productosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_productosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_productosActionPerformed

    private void campo_productosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_productosKeyReleased
        DefaultTableModel model = (DefaultTableModel) registros_productos.getModel();
        model.setRowCount(0);
        int p = 0;
        aux= new String[0];
        if(filtro.getSelectedIndex()==0){
            ResultSet s = c.consulta("select p.PROD_CODIGO,p.PROD_DESCRIPCION,p.PROD_STOCK,p.PROD_PRECIO_UNITARIO,pr.prov_descripcion,p.PROV_CODIGO \n" +
                "from productos p, proveedores pr where pr.prov_codigo=p.prov_codigo and p.prod_estado='AC' and p.PROD_CODIGO like  '%"+campo_productos.getText()+"%' order by PROD_CODIGO asc");
            try {
                while(s.next()){
                    Object v[]= new Object[5];
                    v[0]=s.getObject(1);
                    v[1]=s.getObject(2);
                    v[2]=s.getObject(3);
                    v[3]=s.getObject(4);
                    v[4]=s.getObject(5);
                    aux = Arrays.copyOf(aux, aux.length + 1);
                    aux[p]=String.valueOf(s.getObject(6));
                    p++;
                    model.addRow(v);
                }
                registros_productos.setModel(model);
            } catch (SQLException ex) {
                Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);                
                JOptionPane.showMessageDialog(null, ex.getMessage(), "ERROR",JOptionPane.ERROR_MESSAGE);
            }
        }else if (filtro.getSelectedIndex()==1){
            ResultSet s = c.consulta("select p.PROD_CODIGO,p.PROD_DESCRIPCION,p.PROD_STOCK,p.PROD_PRECIO_UNITARIO,pr.prov_descripcion,p.PROV_CODIGO \n" +
                "from productos p, proveedores pr where pr.prov_codigo=p.prov_codigo and p.prod_estado='AC' and p.PROD_DESCRIPCION like  '%"+campo_productos.getText()+"%' order by PROD_CODIGO asc");
            try {
                while(s.next()){
                    Object v[]= new Object[5];
                    v[0]=s.getObject(1);
                    v[1]=s.getObject(2);
                    v[2]=s.getObject(3);
                    v[3]=s.getObject(4);
                    v[4]=s.getObject(5);
                    aux = Arrays.copyOf(aux, aux.length + 1);
                    aux[p]=String.valueOf(s.getObject(6));
                    p++;
                    model.addRow(v);
                }
                registros_productos.setModel(model);
            } catch (SQLException ex) {
                Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);                
                JOptionPane.showMessageDialog(null, ex.getMessage(), "ERROR",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_campo_productosKeyReleased

    private void campo_productosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_productosKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_productosKeyTyped

    private void registros_productosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registros_productosMouseClicked
        codigo.setText(""+registros_productos.getValueAt(registros_productos.getSelectedRow(),0));
        descripcion.setText(""+registros_productos.getValueAt(registros_productos.getSelectedRow(),1));
        proveedor.setText(""+registros_productos.getValueAt(registros_productos.getSelectedRow(),4));
        cod_prov = aux[registros_productos.getSelectedRow()];
        campo_productos.setText("Ingrese Valor de Busqueda....");
        temp = panel.getComponentAt(1);
        panel.removeTabAt(1);

        precio.requestFocus();
    }//GEN-LAST:event_registros_productosMouseClicked

    private void filtroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_filtroItemStateChanged

    }//GEN-LAST:event_filtroItemStateChanged

    private void campoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoFocusGained
        if(campo.getText().trim().toLowerCase().equals("ingrese valor de busqueda....")){
            campo.setText("");
        }
    }//GEN-LAST:event_campoFocusGained

    private void campoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoFocusLost
        if( campo.getText().trim().equals("") || campo.getText().trim().toLowerCase().equals("ingrese valor de busqueda....")){
            campo.setText("Ingrese Valor de Busqueda....");
        }
    }//GEN-LAST:event_campoFocusLost

    private void campoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoActionPerformed

    private void campoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoKeyReleased
        DefaultTableModel model = (DefaultTableModel) registros_proveedores.getModel();
        model.setRowCount(0);
        Object vector[]= new Object[2];
        if(filtro.getSelectedIndex()==0){
            try {
                ResultSet aux =  c.consulta("select PROV_CODIGO,PROV_DESCRIPCION from proveedores where PROV_CODIGO like  '%"+campo.getText()+"%' and PROV_ESTADO='AC' order by PROV_CODIGO asc");
                while(aux.next()){
                    for(int i=0;i<2;i++){
                        vector[i] = aux.getObject(i+1);
                    }
                    model.addRow(vector);
                }
            } catch (SQLException ex) {
                Logger.getLogger(Compras.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if (filtro.getSelectedIndex()==1){
            try {
                ResultSet aux =  c.consulta("select PROV_CODIGO,PROV_DESCRIPCION from proveedores where PROV_DESCRIPCION like  '%"+campo.getText()+"%' and PROV_ESTADO='AC' order by PROV_CODIGO asc");
                while(aux.next()){
                    for(int i=0;i<2;i++){
                        vector[i] = aux.getObject(i+1);
                    }
                    model.addRow(vector);
                }
            } catch (SQLException ex) {
                Logger.getLogger(Compras.class.getName()).log(Level.SEVERE, null, ex);                
                JOptionPane.showMessageDialog(null, ex.getMessage(), "ERROR",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_campoKeyReleased

    private void campoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoKeyTyped
        char n = evt.getKeyChar();
        if(Character.isLetter(n)){
            String cad = (""+n).toUpperCase();
            n=cad.charAt(0);
            evt.setKeyChar(n);
        }
    }//GEN-LAST:event_campoKeyTyped

    private void registros_proveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registros_proveedoresMouseClicked
        cod_prov = String.valueOf(registros_proveedores.getValueAt(registros_proveedores.getSelectedRow(),0));
        proveedor.setText(""+registros_proveedores.getValueAt(registros_proveedores.getSelectedRow(),1));
        precio.requestFocus();
        campo.setText("Ingrese Valor de Busqueda....");
        temp = panel.getComponentAt(1);
        panel.removeTabAt(1);
    }//GEN-LAST:event_registros_proveedoresMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscar;
    private javax.swing.JTextField campo;
    private javax.swing.JTextField campo_productos;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField cantidad;
    private javax.swing.JTextField codigo;
    private javax.swing.JTextField descripcion;
    private com.toedter.calendar.JDateChooser fecha;
    private javax.swing.JComboBox<String> filtro;
    private javax.swing.JComboBox<String> filtro_productos;
    private javax.swing.JButton guardar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane panel;
    private javax.swing.JTextField precio;
    private javax.swing.JPanel productos;
    private javax.swing.JTextField proveedor;
    private javax.swing.JTable registros_productos;
    private javax.swing.JTable registros_proveedores;
    private javax.swing.JPanel ventana_buscar;
    private javax.swing.JPanel ventana_principal;
    // End of variables declaration//GEN-END:variables
}
